document.writeln("<style>       ");
document.writeln("    .custom-image {");
document.writeln("        width: 133px;");
document.writeln("        height: 33;");
document.writeln("      vertical-align: bottom;");
document.writeln("    }");
document.writeln("input[type=\'text\'] {");
document.writeln("  height: 18px;");
document.writeln("}");
document.writeln("</style>");
document.writeln("<table width=\'1024\' border=\'0\' align=\'center\'>");
document.writeln("<td height=\'33\' align=\'center\' >");
document.writeln("<form onsubmit=\'return baiduWithHttps(this)\' action=\'https://www.baidu.com/baidu\' target=\'_blank\' autocomplete=\'off\'>");
document.writeln("<a href=\'https://www.baidu.com/\' target=\'_blank\'><img src=\'im/baidu.png\' alt=\'Baidu\' align=\'bottom\' border=\'0\' class=\'custom-image\'></a>");
document.writeln("<input type=\'text\'  onfocus=\'checkHttps\' name=\'word\'  size=\'30\'>");
document.writeln("<input type=\'submit\'value=\'百度搜索\'>");
document.writeln("</form>");
document.writeln("</td>");
document.writeln("</table>");