document.writeln("<table width=\'888\' border=\'0\' align=\'center\' style=\'text-align:center;\' >");
document.writeln("  <tr>");
document.writeln("    <td colspan=\'7\' align=\'center\'>&nbsp;</td>");
document.writeln("  </tr>");
document.writeln("<td style=\'text-align: center;\'>");
document.writeln("    <span style=\'color: red; font-size: 18px;\'>分享网站</span>");
document.writeln("</td>");
document.writeln("<td>&nbsp</td>");
document.writeln("<td>&nbsp</td>");
document.writeln("<td>&nbsp</td>");
document.writeln("<td>&nbsp</td>");
document.writeln("<td>&nbsp</td>");
document.writeln("<td style=\'text-align:left;\'>");
document.writeln("    <a href=\'https://www.google.com/\' target=\'_blank\' style=\'color: ; font-size: 16px;\'>更多</a>");
document.writeln("</td>");
document.writeln("    <tr style=\'text-align:left;\'>");
document.writeln("    <td align=\'center\'><font color=\'blue\'>门户</font></td>");
document.writeln("    <td><a href=\'https://www.eastmoney.com/\' target=\'_blank\'>东方财富</a></td>");
document.writeln("    <td><a href=\'https://www.sina.com.cn/\' target=\'_blank\'>新浪</a></td>");
document.writeln("    <td><a href=\'https://www.163.com/\' target=\'_blank\'>网易</a></td>");
document.writeln("    <td><a href=\'https://www.sohu.com/\' target=\'_blank\'>搜狐</a></td>");
document.writeln("    <td><a href=\'https://www.qq.com/\' target=\'_blank\'>腾讯</a></td>");
document.writeln("    <td><a href=\'https://www.google.com/\' target=\'_blank\'>谷歌</a></td>");
document.writeln("  </tr>");
document.writeln("  <tr style=\'text-align:left;\'>");
document.writeln("    <td align=\'center\'><font color=\'blue\'>系统</font></td>");
document.writeln("    <td><a href=\'https://hellowindows.cn/\' target=\'_blank\'>微软下载</a></td>");
document.writeln("    <td><a href=\'https://www.runoob.com/\' target=\'_blank\'>菜鸟教程</a></td>  ");
document.writeln("    <td><a href=\'http://bbs.wuyou.net/\' target=\'_blank\'>无忧启动</a></td>");
document.writeln("    <td><a href=\'https://www.52pojie.cn/\' target=\'_blank\'>吾爱破解</a></td>");
document.writeln("    <td><a href=\'https://bbs.pcbeta.com/\' target=\'_blank\'>远景论坛</a></td>");
document.writeln("    <td><a href=\'https://bbs.kafan.cn/\' target=\'_blank\'>卡饭论坛</a></td>    ");
document.writeln("  </tr>");
document.writeln("  <tr style=\'text-align:left;\'>");
document.writeln("    <td align=\'center\'><font color=\'blue\'>网络</font></td>");
document.writeln("    <td><a href=\'https://cloud.tencent.com/\' target=\'_blank\'>腾讯云</a></td>");
document.writeln("    <td><a href=\'https://www.aliyun.com/\' target=\'_blank\'>阿里云</a></td>");
document.writeln("    <td><a href=\'https://www.yisu.com//\' target=\'_blank\'>亿速云</a></td>");
document.writeln("    <td><a href=\'https://www.lanzou.com/\' target=\'_blank\'>蓝奏网盘</a></td>");
document.writeln("    <td><a href=\'https://wormhole.app/\' target=\'_blank\'>虫洞中转</a></td>");
document.writeln("    <td><a href=\'https://www.aliyundrive.com/\' target=\'_blank\'>阿里网盘</a></td>");
document.writeln("  </tr>");
document.writeln("  <tr style=\'text-align:left;\'>");
document.writeln("    <td align=\'center\'><font color=\'blue\'>游戏</font></td>");
document.writeln("    <td><a href=\'https://www.17173.com/\' target=\'_blank\'>17173</a></td>");
document.writeln("    <td><a href=\'https://www.ali213.net/\' target=\'_blank\'>游侠网</a></td>");
document.writeln("    <td><a href=\'https://www.gamersky.com/\' target=\'_blank\'>游民星空</a></td>");
document.writeln("    <td><a href=\'https://bbs.nga.cn/\' target=\'_blank\'>NGA论坛</a></td>");
document.writeln("    <td><a href=\'https://www.zol.com.cn/\' target=\'_blank\'>中关村</a></td>");
document.writeln("    <td><a href=\'https://www.landiannews.com/\' target=\'_blank\'>蓝点网</a></td>");
document.writeln("  </tr>");
document.writeln("  <tr style=\'text-align:left;\'> ");
document.writeln("    <td align=\'center\'><font color=\'blue\'>娱乐</font></td>");
document.writeln("    <td><a href=\'https://www.douyu.com/\' target=\'_blank\'>斗鱼直播</a></td>");
document.writeln("    <td><a href=\'https://www.huya.com/\' target=\'_blank\'>虎牙直播</a></td>");
document.writeln("    <td><a href=\'https://www.douyin.com/\' target=\'_blank\'>抖音</a></td>");
document.writeln("    <td><a href=\'https://www.bilibili.com/\' target=\'_blank\'>哔哩BiLi</a></td>");
document.writeln("    <td><a href=\'https://nba.hupu.com/\' target=\'_blank\'>虎扑NBA</a></td>");
document.writeln("    <td><a href=\'https://www.zhibo8.cc/\' target=\'_blank\'>直播吧</a></td>  ");
document.writeln("  </tr>");
document.writeln("  <tr style=\'text-align:left;\'>");
document.writeln("    <td align=\'center\'><font color=\'blue\'>购物</font></td>");
document.writeln("    <td><a href=\'https://www.taobao.com/\' target=\'_blank\'>淘宝网</a></td>");
document.writeln("    <td><a href=\'https://www.jd.com/\' target=\'_blank\'>京东商城</a></td>");
document.writeln("    <td><a href=\'https://www.suning.com/\' target=\'_blank\'>苏宁易购</a></td>");
document.writeln("    <td><a href=\'https://www.yiche.com/\' target=\'_blank\'>易车网</a></td>");
document.writeln("    <td><a href=\'https://www.autohome.com.cn\' target=\'_blank\'>汽车之家</a></td>");
document.writeln("    <td><a href=\'https://www.pcauto.com.cn/\' target=\'_blank\'>太平洋汽车</a></td>   ");
document.writeln("  </tr>");
document.writeln("</table>");
document.writeln("<p>&nbsp;</p>");
document.writeln("<div style=\'text-align:center;font-size:0;\'>");
document.writeln("</div>");
