document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("    <title>搜索框示例</title>");
document.writeln("    <style>");
document.writeln("        /* 搜索框容器样式 */");
document.writeln("        .search-container {");
document.writeln("            text-align: center;");
document.writeln("            margin: 20px auto;");
document.writeln("            max-width: 600px;");
document.writeln("        }");
document.writeln("");
document.writeln("        /* 搜索框样式 */");
document.writeln("        .search-box {");
document.writeln("            display: flex;");
document.writeln("            justify-content: center;");
document.writeln("            align-items: stretch; /* 确保所有子元素高度一致 */");
document.writeln("        }");
document.writeln("");
document.writeln("        /* 搜索引擎图标 */");
document.writeln("        .icon {");
document.writeln("            width: 40px;");
document.writeln("            height: 40px;");
document.writeln("            background-size: cover;");
document.writeln("            background-position: center;");
document.writeln("            border: 1px solid #ccc;");
document.writeln("            border-right: none; /* 去掉右侧边框，与输入框无缝衔接 */");
document.writeln("            border-radius: 5px 0 0 5px;");
document.writeln("            box-sizing: border-box; /* 确保边框包含在高度内 */");
document.writeln("            cursor: pointer; /* 设置鼠标指针为手型 */");
document.writeln("        }");
document.writeln("");
document.writeln("        /* 输入框 */");
document.writeln("        .search-box input[type=\'text\'] {");
document.writeln("            width: 300px;");
document.writeln("            padding: 10px;");
document.writeln("            font-size: 16px;");
document.writeln("            border: 1px solid #ccc;");
document.writeln("            border-left: none; /* 去掉左侧边框，与图标无缝衔接 */");
document.writeln("            border-right: none; /* 去掉右侧边框，与选择框无缝衔接 */");
document.writeln("            outline: none;");
document.writeln("            box-sizing: border-box; /* 确保边框和内边距包含在高度内 */");
document.writeln("            height: 40px; /* 固定高度 */");
document.writeln("        }");
document.writeln("");
document.writeln("        /* 选择框 */");
document.writeln("        .search-box select {");
document.writeln("            padding: 10px;");
document.writeln("            font-size: 16px;");
document.writeln("            border: 1px solid #ccc; /* 保留完整的边框 */");
document.writeln("            border-right: none; /* 去掉右侧边框，与按钮无缝衔接 */");
document.writeln("            background-color: #fff;");
document.writeln("            cursor: pointer;");
document.writeln("            box-sizing: border-box; /* 确保边框包含在高度内 */");
document.writeln("            height: 40px; /* 固定高度 */");
document.writeln("        }");
document.writeln("");
document.writeln("        /* 按钮 */");
document.writeln("        .search-box button {");
document.writeln("            padding: 10px 20px;");
document.writeln("            font-size: 16px;");
document.writeln("            background-color: #0073e6;");
document.writeln("            color: #fff;");
document.writeln("            border: none;");
document.writeln("            border-radius: 0 5px 5px 0;");
document.writeln("            cursor: pointer;");
document.writeln("            box-sizing: border-box; /* 确保内边距包含在高度内 */");
document.writeln("            height: 40px; /* 固定高度 */");
document.writeln("        }");
document.writeln("");
document.writeln("        /* 按钮悬停效果 */");
document.writeln("        .search-box button:hover {");
document.writeln("            background-color: #005bb5;");
document.writeln("        }");
document.writeln("    </style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("");
document.writeln("<div class=\'search-container\'>");
document.writeln("    <div class=\'search-box\'>");
document.writeln("        <div class=\'icon\' id=\'search-icon\' style=\'background-image: url(\'IM/baidu.ico\');\'></div>");
document.writeln("        <input type=\'text\' id=\'search-input\' placeholder=\'请输入搜索内容\'>");
document.writeln("        <select id=\'search-engine\'>");
document.writeln("            <option value=\'https://www.baidu.com/s?wd=\' data-url=\'https://www.baidu.com\'>百度</option>");
document.writeln("            <option value=\'https://www.google.com/search?q=\' data-url=\'https://www.google.com\'>Google</option>");
document.writeln("            <option value=\'https://www.bing.com/search?q=\' data-url=\'https://www.bing.com\'>Bing</option>");
document.writeln("        </select>");
document.writeln("        <button id=\'search-button\'>搜索一下</button>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("");
document.writeln("<script>");
document.writeln("    // 搜索引擎图标映射");
document.writeln("    const engineIcons = {");
document.writeln("        \'https://www.baidu.com/s?wd=\': \'im/ss/baidu.ico\',");
document.writeln("        \'https://www.google.com/search?q=\': \'im/ss/google.ico\',");
document.writeln("        \'https://www.bing.com/search?q=\': \'im/ss/bing.ico\'");
document.writeln("    };");
document.writeln("");
document.writeln("    // 页面加载时设置默认图标");
document.writeln("    window.onload = function () {");
document.writeln("        const searchEngineSelect = document.getElementById(\'search-engine\');");
document.writeln("        const selectedEngine = searchEngineSelect.value;");
document.writeln("");
document.writeln("        // 设置默认图标");
document.writeln("        document.getElementById(\'search-icon\').style.backgroundImage = `url(\'${engineIcons[selectedEngine]}\')`;");
document.writeln("    };");
document.writeln("");
document.writeln("    // 监听搜索引擎选择变化");
document.writeln("    document.getElementById(\'search-engine\').addEventListener(\'change\', function () {");
document.writeln("        const selectedEngine = this.value;");
document.writeln("");
document.writeln("        // 更新图标背景图片");
document.writeln("        document.getElementById(\'search-icon\').style.backgroundImage = `url(\'${engineIcons[selectedEngine]}\')`;");
document.writeln("    });");
document.writeln("");
document.writeln("    // 搜索功能");
document.writeln("    function performSearch() {");
document.writeln("        const searchInput = document.getElementById(\'search-input\').value;");
document.writeln("        const searchEngine = document.getElementById(\'search-engine\').value;");
document.writeln("        if (searchInput.trim() !== \'\') {");
document.writeln("            window.open(searchEngine + encodeURIComponent(searchInput), \'_blank\');");
document.writeln("        } else {");
document.writeln("            alert(\'请输入搜索内容！\');");
document.writeln("        }");
document.writeln("    }");
document.writeln("");
document.writeln("    // 绑定搜索按钮点击事件");
document.writeln("    document.getElementById(\'search-button\').addEventListener(\'click\', performSearch);");
document.writeln("");
document.writeln("    // 回车键触发搜索");
document.writeln("    document.getElementById(\'search-input\').addEventListener(\'keypress\', function (e) {");
document.writeln("        if (e.key === \'Enter\') {");
document.writeln("            performSearch();");
document.writeln("        }");
document.writeln("    });");
document.writeln("");
document.writeln("    // 搜索图标点击事件");
document.writeln("    document.getElementById(\'search-icon\').addEventListener(\'click\', function () {");
document.writeln("        const searchEngineSelect = document.getElementById(\'search-engine\');");
document.writeln("        const selectedOption = searchEngineSelect.options[searchEngineSelect.selectedIndex];");
document.writeln("        const engineUrl = selectedOption.getAttribute(\'data-url\');");
document.writeln("        window.open(engineUrl, \'_blank\');");
document.writeln("    });");
document.writeln("</script>");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>");