document.writeln("<style>");
document.writeln("  .video-container {");
document.writeln("    display: flex;");
document.writeln("    justify-content: center; /* 水平居中 */");
document.writeln("    align-items: center;     /* 垂直居中 */");
document.writeln("    width: 1024px;          /* 设置容器宽度 */");
document.writeln("    margin: 0 auto;         /* 页面居中 */");
document.writeln("  }");
document.writeln("");
document.writeln("  .video-wrapper {");
document.writeln("    width: 480px;          /* 视频宽度 */");
document.writeln("    height: 309px;         /* 视频高度 */");
document.writeln("    position: relative;   /* 用于定位链接 */");
document.writeln("  }");
document.writeln("");
document.writeln("  .video-wrapper video {");
document.writeln("    width: 100%;");
document.writeln("    height: 100%;");
document.writeln("    display: block;");
document.writeln("    mix-blend-mode: screen;");
document.writeln("  }");
document.writeln("");
document.writeln("  .video-wrapper a {");
document.writeln("    position: absolute;");
document.writeln("    top: 0;");
document.writeln("    left: 0;");
document.writeln("    width: 100%;");
document.writeln("    height: 100%;");
document.writeln("    display: block;");
document.writeln("  }");
document.writeln("</style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("");
document.writeln("<div class=\'video-container\'>");
document.writeln("  <div class=\'video-wrapper\'>");
document.writeln("    <a href=\'www.sxso.cn/\'>");
document.writeln("      <video src=\'im/helloworld.mp4\' title=\'欢迎进入云彩天际网站\' autoplay muted loop></video>");
document.writeln("    </a>");
document.writeln("  </div>");
document.writeln("</div>");
document.writeln("");
document.writeln("<script>");
document.writeln("  document.addEventListener(\'DOMContentLoaded\', function() {");
document.writeln("    const video = document.querySelector(\'video\');");
document.writeln("    video.addEventListener(\'contextmenu\', function(event) {");
document.writeln("      event.preventDefault();");
document.writeln("    });");
document.writeln("  });");
document.writeln("</script>");
